# =============================================================
# Configuração do Banco de Dados (Dinâmica para Local e Docker)
# =============================================================
# No PC usa localhost:5444. No Docker, ele vai buscar as variáveis que configuramos.
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5444}/${DB_NAME:portal_transparencia}
spring.datasource.username=${DB_USER:admin}
spring.datasource.password=${DB_PASSWORD:@jn87519023}
spring.datasource.driver-class-name=org.postgresql.Driver

# =============================================================
# Configurações do JPA / Hibernate
# =============================================================
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# =============================================================
# Configurações do Servidor
# =============================================================
spring.application.name=portal-transparencia-api
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
server.port=8080
spring.profiles.active=local