name: Deploy API

on:
  push:
    branches: [ main ]
    paths:
      - 'portal-transparencia-api/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Login no GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build e Push da Imagem Docker
        uses: docker/build-push-action@v5
        with:
          context: ./portal-transparencia-api
          push: true
          # AQUI: Escrevemos em minúsculo para o Docker não reclamar
          tags: ghcr.io/jacksonnascimento/horizon-api:latest

      - name: Comandar a VPS via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/horizon
            # AQUI TAMBÉM: Nome em minúsculo
            export DOCKER_IMAGE_API=ghcr.io/jacksonnascimento/horizon-api:latest
            docker compose pull horizon-api
            docker compose up -d horizon-api